"""changed restriction extenstions for hotels

Revision ID: 6f8a720f4dca
Revises: b136af04fda4
Create Date: 2024-08-18 14:06:27.243005

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '6f8a720f4dca'
down_revision: Union[str, None] = 'b136af04fda4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
